---
name: lennart_epp
channels: [conda-forge, nodefaults]
dependencies:
  - python ==3.12
  - pip >=21.1

  # Development dependencies
  - conda-lock
  - ipykernel
  - jupyterlab
  - pre-commit

  # Language agnostic template project dependencies
  - pytask >=0.5.0
  - pytask-latex >=0.4.2
  - pytask-parallel >=0.5.0
  - pytest
  - pytest-cov
  - pytest-xdist

  # Python template project dependencies
  - statsmodels >=0.14  # For ADF test in AR(p) model
  - numpy >=1.26
  - pandas >=2.2
  - plotly >=5.2.0,<6
  - yfinance  # added yfinance
  - scikit-learn >=1.0

  # Install project
  - pip: [-e ., pdbp, kaleido, arch >=5.1, nolds]
